/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ef4444",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#4ade80",
        "tertiary-fixed-dim": "#fcd34d",
        "secondary-fixed-dim": "#60a5fa",
        "primary-fixed": "#22c55e",
        "outline-variant": "#e5e7eb",
        "primary-container": "#dcfce7",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#fee2e2",
        "inverse-on-surface": "#f9fafb",
        "surface-container": "#f3f4f6",
        "on-primary-fixed-variant": "#166534",
        "surface-variant": "#f3f4f6",
        "tertiary-fixed": "#fde68a",
        "on-primary-container": "#14532d",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#78350f",
        "surface-container-low": "#f9fafb",
        "inverse-primary": "#86efac",
        "on-secondary-fixed": "#1e3a8a",
        "on-error": "#ffffff",
        "surface": "#ffffff",
        "surface-container-highest": "#e5e7eb",
        "surface-tint": "#4ade80",
        "inverse-surface": "#1f2937",
        "on-background": "#111827",
        "on-tertiary-fixed-variant": "#b45309",
        "on-primary-fixed": "#14532d",
        "on-error-container": "#991b1b",
        primary: "#4ade80",
        background: "#f9fbfc",
        secondary: "#60a5fa",
        "surface-container-high": "#e5e7eb",
        "secondary-container": "#dbeafe",
        "on-secondary-container": "#1e3a8a",
        "on-surface": "#111827",
        "secondary-fixed": "#bfdbfe",
        "surface-dim": "#d1d5db",
        "on-surface-variant": "#6b7280",
        "tertiary-container": "#fef3c7",
        "on-tertiary": "#ffffff",
        outline: "#9ca3af",
        "on-tertiary-container": "#92400e",
        "on-secondary-fixed-variant": "#2563eb",
        tertiary: "#fcd34d",
        "fm-green": "#4ade80",
        "fm-orange": "#f97316",
        "fm-gold": "#fcd34d",
        "fm-red": "#ef4444",
        "fm-muted": "#9ca3af"
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        sm: "0.375rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
        full: "9999px"
      },
      fontFamily: {
        "display-lg": ["Bebas Neue", "sans-serif"],
        "headline-lg": ["Bebas Neue", "sans-serif"],
        "headline-md": ["Bebas Neue", "sans-serif"],
        "label-md": ["Poppins", "sans-serif"],
        "label-sm": ["Poppins", "sans-serif"],
        "body-lg": ["Poppins", "sans-serif"],
        "body-md": ["Poppins", "sans-serif"],
        "display": ["Bebas Neue", "sans-serif"],
        "mono": ["Poppins", "monospace"], 
      },
      boxShadow: {
        'subtle-card': '0 10px 40px -10px rgba(0,0,0,0.06)',
        'neon-primary': '0 8px 20px rgba(74, 222, 128, 0.25)',
        'neon-accent': '0 8px 20px rgba(74, 222, 128, 0.25)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
        'pulse-fast': 'pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'glow-pulse': 'glowPulse 3s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        glowPulse: {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        }
      },
      backgroundImage: {
        'stadium-pattern': "none",
        'pitch-pattern': "none"
      }
    },
  },
  plugins: [],
}
