/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ef4444",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#f97316",
        "tertiary-fixed-dim": "#f43f5e",
        "secondary-fixed-dim": "#3b82f6",
        "primary-fixed": "#fdba74",
        "outline-variant": "#e2e8f0",
        "primary-container": "#ffedd5",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#fee2e2",
        "inverse-on-surface": "#f8fafc",
        "surface-container": "#f1f5f9",
        "on-primary-fixed-variant": "#c2410c",
        "surface-variant": "#f1f5f9",
        "tertiary-fixed": "#fda4af",
        "on-primary-container": "#9a3412",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#4c0519",
        "surface-container-low": "#f8fafc",
        "inverse-primary": "#ffedd5",
        "on-secondary-fixed": "#1e3a8a",
        "on-error": "#ffffff",
        "surface": "#ffffff",
        "surface-container-highest": "#e2e8f0",
        "surface-tint": "#F26522",
        "inverse-surface": "#0f172a",
        "on-background": "#0f172a",
        "on-tertiary-fixed-variant": "#e11d48",
        "on-primary-fixed": "#431407",
        "on-error-container": "#991b1b",
        primary: "#F26522",
        background: "#f8fafc",
        secondary: "#3b82f6",
        "surface-container-high": "#e2e8f0",
        "secondary-container": "#dbeafe",
        "on-secondary-container": "#1e40af",
        "on-surface": "#0f172a",
        "secondary-fixed": "#bfdbfe",
        "surface-dim": "#cbd5e1",
        "on-surface-variant": "#64748b",
        "tertiary-container": "#ffe4e6",
        "on-tertiary": "#ffffff",
        outline: "#94a3b8",
        "on-tertiary-container": "#9f1239",
        "on-secondary-fixed-variant": "#1d4ed8",
        tertiary: "#f43f5e",
        "fm-green": "#22c55e",
        "fm-orange": "#F26522",
        "fm-gold": "#eab308",
        "fm-red": "#ef4444",
        "fm-muted": "#94a3b8"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      fontFamily: {
        "display-lg": ["Teko", "sans-serif"],
        "headline-lg": ["Teko", "sans-serif"],
        "headline-md": ["Teko", "sans-serif"],
        "label-md": ["Bebas Neue", "sans-serif"],
        "label-sm": ["Bebas Neue", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display": ["Teko", "sans-serif"],
        "mono": ["Bebas Neue", "monospace"], 
      },
      boxShadow: {
        'subtle-card': '0 4px 20px rgba(0, 0, 0, 0.05)',
        'neon-primary': '0 0 15px rgba(242, 101, 34, 0.3)',
        'neon-accent': '0 0 15px rgba(59, 130, 246, 0.3)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
        'pulse-fast': 'pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        }
      },
      backgroundImage: {
        'stadium-pattern': "url('https://images.unsplash.com/photo-1518605368461-1ee7e54c86e0?q=80&w=2000&auto=format&fit=crop')",
        'pitch-pattern': "linear-gradient(rgba(248, 250, 252, 0.9), rgba(248, 250, 252, 0.97)), url('data:image/svg+xml,%3Csvg width=\\'60\\' height=\\'60\\' viewBox=\\'0 0 60 60\\' xmlns=\\'http://www.w3.org/2000/svg\\'%3E%3Cg fill=\\'none\\' fill-rule=\\'evenodd\\'%3E%3Cg fill=\\'%23cbd5e1\\' fill-opacity=\\'0.15\\'%3E%3Cpath d=\\'M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z\\'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E')"
      }
    },
  },
  plugins: [],
}
